server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:wallet}
    username: ${POSTGRES_NAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    enabled: true

  jpa:
    open-in-view: false